

name: deploy-container-2


on:

  push:
    branches: [ master ]
    paths:
    - 'packages/container/**'

  pull_request:
    branches: [ master ]

  workflow_dispatch:

defaults:
   run:
    working-directory: packages/container   
    
jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: shinyinc/action-aws-cli@v1.2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S_BUCKET_NAME}}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}

